### ISSUE TITLE
MCServerPing crash when hide-online-players==true in 21w44a

### ISSUE THREAD

**Issue by RedTeaDev** [RedCokeDevelopment/MCServerPing#7]
**Describe the bug**

**To Reproduce**
1.  Open a minecraft server in 21w44a
2.  Join minecraft server
3.  `MCServerPing.getPing("{server}", 25565);`

**Expected behavior**

Should not throw NullPointer

**Screenshots**
![image](https://user-images.githubusercontent.com/51795815/141125923-1b578737-7957-4d3f-affb-6f62f705cfe6.png)
![image](https://user-images.githubusercontent.com/51795815/141125953-41c16c8b-0761-44e5-b64b-a609f34b9290.png)

**Additional context**
Add any other context about the problem here [e.g. error logs, crash logs, etc...].

```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
        at dev.redcoke.mcserverping.MCServerPingResponse.serverPingFromJsonObj(MCServerPingResponse.java:38)
        at dev.redcoke.mcserverping.MCServerPing.getPing(MCServerPing.java:157)
        at dev.redcoke.mcserverping.MCServerPing.getPing(MCServerPing.java:35)
        at dev.redcoke.teapot.externalapi.java.MineCraftServerPing.getPing(MineCraftServerPing.java:10)
        at dev.redcoke.teapot.command.commands.MinecraftServer.lambda$handle$0(MinecraftServer.java:26)
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by RedTeaDev** [comment]
github fault 🤦  check #8 instead
