### ISSUE TITLE
favicon could be null, causing MCServerPing throws NullpointerException

### ISSUE THREAD

**Issue by RedTeaDev** [RedCokeDevelopment/MCServerPing#8]
**Describe the bug**

MCServerPing throw Nullpointer 

**To Reproduce**
1.  Open a minecraft server ~~in 21w44a~~
2.  Join minecraft server
3.  `MCServerPing.getPing("{server}", 25565);`

**Expected behavior**

Should not throw NullPointer

**Screenshots**
![image](https://user-images.githubusercontent.com/51795815/141125923-1b578737-7957-4d3f-affb-6f62f705cfe6.png)
![image](https://user-images.githubusercontent.com/51795815/141125953-41c16c8b-0761-44e5-b64b-a609f34b9290.png)

**Additional context**
Add any other context about the problem here [e.g. error logs, crash logs, etc...].

```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
        at dev.redcoke.mcserverping.MCServerPingResponse.serverPingFromJsonObj(MCServerPingResponse.java:38)
        at dev.redcoke.mcserverping.MCServerPing.getPing(MCServerPing.java:157)
        at dev.redcoke.mcserverping.MCServerPing.getPing(MCServerPing.java:35)
        at dev.redcoke.teapot.externalapi.java.MineCraftServerPing.getPing(MineCraftServerPing.java:10)
        at dev.redcoke.teapot.command.commands.MinecraftServer.lambda$handle$0(MinecraftServer.java:26)
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Effected Version:
- Since 0.1 -> 0.1.1

**Comment by binary1024x2** [comment]
I'm using version 0.1.4 and it is still happening... Had to copy the source and fix it to make it work

**Comment by ColaIan** [comment]
> I'm using version 0.1.4 and it is still happening... Had to copy the source and fix it to make it work

Could you provide more details such as what mc server har are you using, code and screenshot?

**Comment by binary1024x2** [comment]
Screenshot of the error

![imagen](https://github.com/RedCokeDevelopment/MCServerPing/assets/132934948/f79b4a3a-7dd8-483f-9973-1955c0664d30)

Screenshot of the `build.gradle`

![imagen](https://github.com/RedCokeDevelopment/MCServerPing/assets/132934948/76e4f3ff-54f3-4468-858c-fa06f03bd275)

Had to exclude `bungeecord-api` as the version on the `pom.xml` won't let Gradle compile, and I'm using this version as it is available on Maven.

```gradle
implementation 'net.md-5:bungeecord-api:1.16-R0.4'
```

Also using a newer version of  Gson already on my `build.gradle`

```gradle
implementation 'com.google.code.gson:gson:2.10.1'
```

Code Snipped
```java
@Override
    public void run() {
        try {
            String[] ipport = ip.split(":");
            MCServerPingResponse response;
            if (ipport.length == 1) {
                response = MCServerPing.getPing(ipport[0]);
            } else {
                response = MCServerPing.getPing(ipport[0], Integer.parseInt(ipport[1]));
            }
            this.motd = response.getMotd();
        } catch (IOException | TimeoutException ignored) {}
    }
```
This is the (trimmed) response the server sends on [MCServerPing.java, Line 128](https://github.com/RedCokeDevelopment/MCServerPing/blob/44eb9730a94f05a8f338f70cc17752d3ff326e59/src/main/java/dev/redcoke/mcserverping/MCServerPing.java#L128)

```json
{
    "version": {
        "name": "Purpur 1.20.1",
        "protocol": 763
    },
    "description": {
        "extra": [],
        "text": ""
    },
    "players": {
        "max": 25,
        "online": 3,
        "sample": []
    }
}
```

**Comment by RedTeaDev** [comment]
It seems like the issue you are encountering is related to #21 rather than the current one. 

Could you please update or add a comment in issue #21?
